In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df=pd.read_csv(r'cdlj.csv')

In [3]:
df.head()

,Title,Position,HouseIcon,Follow,Tags,TotalPrice,UnitPrice
0,蜀都新邨 3室2厅 西南,蜀都新邨 - 郫县城区,3室2厅 | 110.27平米 | 西南 | 精装 | 高楼层(共18层) | 2014年 ...,6人关注 / 2个月以前发布,"VR看装修,房本满两年",73.8万,"6,693元/平"
1,华侨凤凰国际城 4室2厅 东南 南,华侨凤凰国际城 - 郫县城区,4室2厅 | 106.42平米 | 东南 南 | 精装 | 中楼层(共30层) | 2016...,3人关注 / 3个月以前发布,"VR房源,房本满五年,随时看房",105万,"9,867元/平"
2,香门第名家 5室1厅 西南,香门第名家 - 郫县城区,5室1厅 | 169.2平米 | 西南 | 毛坯 | 高楼层(共6层) | 2020年 | ...,2人关注 / 4个月以前发布,"VR房源,随时看房",395万,"23,346元/平"
3,九龙仓御园二期 3室2厅 南 北,九龙仓御园二期 - 万象城,3室2厅 | 165.22平米 | 南 北 | 毛坯 | 高楼层(共28层) | 2016年...,3人关注 / 1个月以前发布,"近地铁,VR看装修,房本满五年,随时看房",420万,"25,421元/平"
4,春天大道 3室1厅 东,春天大道 - 光华大道沿线,3室1厅 | 135.39平米 | 东 | 精装 | 低楼层(共18层) | 板塔结合,3人关注 / 2个月以前发布,"近地铁,VR看装修,房本满五年,随时看房",162万,"11,966元/平"

In [6]:
df['HouseIcon'][0]

'3室2厅 | 110.27平米 | 西南 | 精装 | 高楼层(共18层) | 2014年 | 板楼'

In [28]:
pattern = re.compile( r'\b(东南|东北|西南|西北|东|南|西|北)\b')
match = pattern.match(df['HouseIcon'][0])

In [61]:
pattern = r'(?:.*\|)?(.*)'

# 使用re.search查找匹配项
match = re.search(pattern, df['HouseIcon'][0])

In [63]:
match.group(1)

' 板楼'

In [4]:
df['room']=df['HouseIcon'].apply(lambda x :re.search(r'\d+室\d+厅',x).group(0))

df['area']=df['HouseIcon'].apply(lambda x :re.search(r'(\d+\.?\d*)\s*平米',x).group(0))

df['direct']=df['HouseIcon'].apply(lambda x :re.search( r'\b(东南|东北|西南|西北|东|南|西|北)\b',x).group(0))

df['type']=df['HouseIcon'].apply(lambda x :re.search( r'(?:\|.*?){2}\|(.+?)\|',x).group(1))

df['floor']=df['HouseIcon'].apply(lambda x :re.search( r'(?:\|.*?){3}\|(.+?)\|',x).group(1))

In [5]:
def yr(a):
    pattern =r'\b\d{4}年\b'
    match = re.search(pattern, df['HouseIcon'][0])
    if match is None:
        return np.nan
    else:
        return match.group(0)

In [6]:
df['year']=df['HouseIcon'].apply(lambda x :yr(x))

In [7]:
df['struct']=df['HouseIcon'].apply(lambda x :re.search(r'(?:.*\|)?(.*)',x).group(1))

In [8]:
df.head()

,Title,Position,HouseIcon,Follow,Tags,TotalPrice,UnitPrice,room,area,direct,type,floor,year,struct
0,蜀都新邨 3室2厅 西南,蜀都新邨 - 郫县城区,3室2厅 | 110.27平米 | 西南 | 精装 | 高楼层(共18层) | 2014年 ...,6人关注 / 2个月以前发布,"VR看装修,房本满两年",73.8万,"6,693元/平",3室2厅,110.27平米,西南,精装,高楼层(共18层),2014年,板楼
1,华侨凤凰国际城 4室2厅 东南 南,华侨凤凰国际城 - 郫县城区,4室2厅 | 106.42平米 | 东南 南 | 精装 | 中楼层(共30层) | 2016...,3人关注 / 3个月以前发布,"VR房源,房本满五年,随时看房",105万,"9,867元/平",4室2厅,106.42平米,东南,精装,中楼层(共30层),2014年,板塔结合
2,香门第名家 5室1厅 西南,香门第名家 - 郫县城区,5室1厅 | 169.2平米 | 西南 | 毛坯 | 高楼层(共6层) | 2020年 | ...,2人关注 / 4个月以前发布,"VR房源,随时看房",395万,"23,346元/平",5室1厅,169.2平米,西南,毛坯,高楼层(共6层),2014年,暂无数据
3,九龙仓御园二期 3室2厅 南 北,九龙仓御园二期 - 万象城,3室2厅 | 165.22平米 | 南 北 | 毛坯 | 高楼层(共28层) | 2016年...,3人关注 / 1个月以前发布,"近地铁,VR看装修,房本满五年,随时看房",420万,"25,421元/平",3室2厅,165.22平米,南,毛坯,高楼层(共28层),2014年,板塔结合
4,春天大道 3室1厅 东,春天大道 - 光华大道沿线,3室1厅 | 135.39平米 | 东 | 精装 | 低楼层(共18层) | 板塔结合,3人关注 / 2个月以前发布,"近地铁,VR看装修,房本满五年,随时看房",162万,"11,966元/平",3室1厅,135.39平米,东,精装,低楼层(共18层),2014年,板塔结合

In [ ]:
del df['HouseIcon']

In [71]:
df['struct'].value_counts()

 板楼      1200
 板塔结合    1000
 塔楼       700
 暂无数据     100
Name: struct, dtype: int64